[package]
name = "day-12"
version = "0.1.0"
authors = ["Mike Purvis <mpurvis@clearpath.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euclid = "0.22.1"
