[package]
name = "day-10"
version = "0.1.0"
authors = ["Mike Purvis <mpurvis@clearpath.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
defaultmap = "0.5.0"
itertools = "0.9.0"
